name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - uses: addnab/docker-run-action@v3
        with:
          # username: ${{ secrets.DOCKER_USERNAME }}
          # password: ${{ secrets.DOCKER_PASSWORD }}
          # registry: gcr.io
          image: maven:3-openjdk-11
          options: -v ${{ github.workspace }}:/usr/src/mymaven:rw -w /usr/src/mymaven
          run: |
            mvn clean install
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "ldap-msad-user-sid-mapper.jar,README.md,LICENSE"
          body: "NEw test release"
          draft: true
          tag: 1.0.0